version: "3"
services:

  dbBanklyUser:
    image: mysql:8.0.30
    volumes:
      - ./config/mysql:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bankly-user
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - 127.0.0.1:3307:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
